### PR TITLE
[ng2] add support menu toggling; exclude all A1 & md1 scripts

### LINKED ISSUE #2703: [ng2] sidenav language drop-down doesn't work

### PR DESCRIPTION
**Pull request by chalin**
Support menu toggling w/o using A1 controller. Menus affected:
- Main menu
- Sidenav
- Language delection menu.

With this commit, we are able to exclude all A1 and MD1 scripts.

Fixes #2703.

### CODE REVIEW

File: public/resources/js/util.js [hunk 1]
```diff
@@ -83,5 +83,14 @@ var NgIoUtil = (function () {
         return NgIoUtil._exampleName;
     };
 
+    NgIoUtil.toggleMenu = function (menu) {
```
Comment (ericjim) [inline public/resources/js/util.js]: Very nice
